[package]
name = "seamctl"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
camino = "1"
clap = { version = "4", features = ["derive"] }
jsonschema = "0.17"
petgraph = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
